services:
  # Main application service
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000" # HTTP API and static files
    volumes:
      # Persistent database storage
      - todo_data:/home/app/data
      # Development: mount source for hot reload (uncomment for dev)
      # - ./server-rs/src:/home/app/src:ro
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:/home/app/data/todos.db
      - STATIC_DIR=./static
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/ssl:/etc/nginx/ssl:ro
    depends_on:
      - todo-app
    restart: unless-stopped
    profiles:
      - production

volumes:
  todo_data:
    driver: local
