global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "todo-app"
    static_configs:
      - targets: ["todo-app:8000"]
    scrape_interval: 5s
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
